encoderEnabled:
snapshotEnabled:
cameraIp:
cameraPort:
snapshotPort:
rtmpStreamPath:
snapshotPath:
accessKey:
secretKey:
awsRegion:
uploadBucket:
localCameraProxy:
ngrokEnabled:
ngrokAuthtoken:
forceRtspTcp:
audioFromCameraEnabled:
overrideVideoExt:
firewallEnabled:
scheduledRecordings: